### ISSUE TITLE
TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by kravciak** [kubewarden/ui#201]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

`install kubewarden` button is not working, clicking it shows error in console.

```
Loading index for repo kubewarden-charts (5ca344d6-4e9e-4252-a284-8a4244c6966b)
GET https://192.168.144.2.nip.io/v1/catalog.cattle.io.clusterrepos/kubewarden-charts?link=index 500
console.js:31 TypeError: Cannot read properties of undefined (reading 'goToInstall')
    at f.chartRoute (InstallView.vue:173:1)
Gr.n.forEach.console.<computed> @ console.js:31
re @ vue.runtime.esm.js:1897
ne @ vue.runtime.esm.js:1888
te @ vue.runtime.esm.js:1848
(anonymous) @ vue.runtime.esm.js:1865
Promise.catch (async)
ee @ vue.runtime.esm.js:1865
n @ vue.runtime.esm.js:2188
Dr.c._wrapper @ vue.runtime.esm.js:6961
```

![Screenshot from 2023-01-12 09-56-18](https://user-images.githubusercontent.com/538604/212024123-fe20e7e7-602d-4d6c-8e58-d261e23b8a39.png)

### Steps To Reproduce

To reproduce it you have to click fast. It's easily reproducible with automation.

0. kubewarden-charts is not added yet. 
1. click `install kubewarden`
2. click `add kubewarden repository`
3. click `install kubewarden`

**Comment by jordojordo** [comment]
I believe this has been fixed with #199 but a new release hasn't been created. I'll push a new release and will test.

**Comment by jordojordo** [comment]
This issue appears to be fixed after the [latest release](https://github.com/kubewarden/ui/releases/tag/kubewarden-0.1.15). Let me know if you're still encountering this after updating.

 
https://user-images.githubusercontent.com/40806497/212100012-beacc0c4-5897-4a14-a978-cf41b209698e.mp4

**Comment by kravciak** [comment]
Now when I click on `Add Kubewarden Repository` button then I get to the next page - but `Install Kubewarden` button never gets enabled. I need to refresh the page.

I tried on rancher 2.7.0 and 2.7.2-rc1.

![test-failed-1](https://user-images.githubusercontent.com/538604/212932291-42946306-d5b3-412d-a90a-e97fef182a80.png)

**Comment by jordojordo** [comment]
@kravciak I've pushed a [new build](https://github.com/kubewarden/ui/releases/tag/kubewarden-0.1.16) that properly refreshes the charts to give an installation route.

**Comment by kravciak** [comment]
I tried kubewarden:0.1.16 but it's still not working.

![Screenshot from 2023-01-18 09-18-10](https://user-images.githubusercontent.com/538604/213119285-b5e8ea8e-bc57-4d5f-bd07-88e430011b69.png)

**Comment by kravciak** [comment]
Sorry to reopen but the fix behaves funky - it shows `Reload` button only for split second, then it disappears and no buttons are visible.
I tested on:
 - google chrome
 - rancher v2.7.2-rc3
 - kubewarden ui 1.0.2 

[Screencast from 2023-02-21 14-30-15.webm](https://user-images.githubusercontent.com/538604/220360218-d2b8aeab-8c1e-48e1-be06-e6c36ee6c1c1.webm)

**Comment by jordojordo** [comment]
This was fixed with https://github.com/kubewarden/ui/pull/250, the change will not appear until the next patch release (`1.0.3`).
